version: '3.8'

services:
  microservice1:
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  microservice2:
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
db:
    image: postgres:13
    environment:
      POSTGRES_DB: postcode_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"